// <auto-generated />
using System;
using EduTrackApi.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EduTrackApi.Infrastructure.Migrations
{
    [DbContext(typeof(EduTrackDbContext))]
    [Migration("20260430213832_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("edutrack")
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EduTrackApi.Domain.Entities.Badge", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("id");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("color");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("icon");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("badges", "edutrack");

                    b.HasData(
                        new
                        {
                            Id = "bg1",
                            Color = "from-orange-400 to-rose-500",
                            Description = "Bir hafta boyunca her gün antrenmana katıldın. Muhteşem süreklilik!",
                            Icon = "🔥",
                            Name = "7 Günlük Seri"
                        },
                        new
                        {
                            Id = "bg2",
                            Color = "from-amber-300 to-orange-500",
                            Description = "Sabah 09:00 öncesindeki antrenmanların yıldızı sensin.",
                            Icon = "🌅",
                            Name = "Erken Kuş"
                        },
                        new
                        {
                            Id = "bg3",
                            Color = "from-indigo-400 to-purple-600",
                            Description = "Aynı gün içerisinde iki farklı branşta eğitim alarak sınırları zorladın.",
                            Icon = "⚡",
                            Name = "Çift Mesai"
                        },
                        new
                        {
                            Id = "bg4",
                            Color = "from-emerald-400 to-teal-600",
                            Description = "Bu ay toplamda 20 saati aşkın antrenman süresine ulaştın.",
                            Icon = "🎯",
                            Name = "Sadık Sporcu"
                        },
                        new
                        {
                            Id = "bg5",
                            Color = "from-blue-400 to-indigo-600",
                            Description = "Eğitmen notlarında üst üste 3 kez \"Üstün Başarı\" yorumu aldın.",
                            Icon = "🚀",
                            Name = "Gelişim Öncüsü"
                        },
                        new
                        {
                            Id = "bg6",
                            Color = "from-pink-400 to-rose-500",
                            Description = "Grup çalışmalarında en çok yardımlaşan öğrenci seçildin.",
                            Icon = "🤝",
                            Name = "Sosyal Kelebek"
                        });
                });

            modelBuilder.Entity("EduTrackApi.Domain.Entities.Branch", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("branches", "edutrack");

                    b.HasData(
                        new
                        {
                            Id = "b1",
                            Name = "Futbol"
                        },
                        new
                        {
                            Id = "b2",
                            Name = "Basketbol"
                        },
                        new
                        {
                            Id = "b3",
                            Name = "Matematik"
                        },
                        new
                        {
                            Id = "b4",
                            Name = "Voleybol"
                        },
                        new
                        {
                            Id = "b5",
                            Name = "Yüzme"
                        });
                });

            modelBuilder.Entity("EduTrackApi.Domain.Entities.Category", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("categories", "edutrack");

                    b.HasData(
                        new
                        {
                            Id = "c1",
                            Name = "U19"
                        },
                        new
                        {
                            Id = "c2",
                            Name = "U15"
                        },
                        new
                        {
                            Id = "c3",
                            Name = "Özel Ders"
                        },
                        new
                        {
                            Id = "c4",
                            Name = "Grup"
                        });
                });

            modelBuilder.Entity("EduTrackApi.Domain.Entities.Course", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<string>("BranchId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("branch_id");

                    b.Property<string>("CategoryId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("category_id");

                    b.Property<string>("InstructorNotes")
                        .HasColumnType("text")
                        .HasColumnName("instructor_notes");

                    b.Property<string>("Location")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("location");

                    b.Property<string>("SchoolId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("school_id");

                    b.Property<string>("TeacherId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("teacher_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("SchoolId");

                    b.HasIndex("TeacherId");

                    b.ToTable("courses", "edutrack");

                    b.HasData(
                        new
                        {
                            Id = "crs1",
                            Address = "41.0082, 28.9784",
                            BranchId = "b1",
                            CategoryId = "c1",
                            InstructorNotes = "Lütfen antrenmana 15 dakika erken gelerek ısınma hareketlerine başlayın. Krampon kontrolü yapılacak.",
                            Location = "A Sahası",
                            SchoolId = "school-a",
                            TeacherId = "u1",
                            Title = "U19 Futbol Elit"
                        },
                        new
                        {
                            Id = "crs2",
                            Address = "Ankara, Çankaya",
                            BranchId = "b3",
                            CategoryId = "c3",
                            InstructorNotes = "Geçen haftaki problem setini yanınızda getirmeyi unutmayın. Türev konusuna giriş yapacağız.",
                            Location = "Z-12 Laboratuvarı",
                            SchoolId = "school-a",
                            TeacherId = "u7",
                            Title = "Matematik İleri Seviye"
                        });
                });

            modelBuilder.Entity("EduTrackApi.Domain.Entities.CourseSchedule", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CourseId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("course_id");

                    b.Property<short>("DayOfWeek")
                        .HasColumnType("smallint")
                        .HasColumnName("day_of_week");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("interval")
                        .HasColumnName("end_time");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("interval")
                        .HasColumnName("start_time");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.ToTable("course_schedules", "edutrack");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CourseId = "crs1",
                            DayOfWeek = (short)1,
                            EndTime = new TimeSpan(0, 18, 0, 0, 0),
                            StartTime = new TimeSpan(0, 16, 0, 0, 0)
                        },
                        new
                        {
                            Id = 2L,
                            CourseId = "crs1",
                            DayOfWeek = (short)4,
                            EndTime = new TimeSpan(0, 18, 0, 0, 0),
                            StartTime = new TimeSpan(0, 16, 0, 0, 0)
                        },
                        new
                        {
                            Id = 3L,
                            CourseId = "crs2",
                            DayOfWeek = (short)1,
                            EndTime = new TimeSpan(0, 20, 0, 0, 0),
                            StartTime = new TimeSpan(0, 18, 30, 0, 0)
                        },
                        new
                        {
                            Id = 4L,
                            CourseId = "crs2",
                            DayOfWeek = (short)3,
                            EndTime = new TimeSpan(0, 20, 0, 0, 0),
                            StartTime = new TimeSpan(0, 18, 30, 0, 0)
                        });
                });

            modelBuilder.Entity("EduTrackApi.Domain.Entities.CourseStudent", b =>
                {
                    b.Property<string>("CourseId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("course_id");

                    b.Property<string>("StudentId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("student_id");

                    b.HasKey("CourseId", "StudentId");

                    b.HasIndex("StudentId");

                    b.ToTable("course_students", "edutrack");

                    b.HasData(
                        new
                        {
                            CourseId = "crs1",
                            StudentId = "u2"
                        },
                        new
                        {
                            CourseId = "crs1",
                            StudentId = "u9"
                        },
                        new
                        {
                            CourseId = "crs2",
                            StudentId = "u2"
                        },
                        new
                        {
                            CourseId = "crs2",
                            StudentId = "u9"
                        });
                });

            modelBuilder.Entity("EduTrackApi.Domain.Entities.Notification", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("id");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean")
                        .HasColumnName("is_read");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<short?>("SenderRoleId")
                        .HasColumnType("smallint")
                        .HasColumnName("sender_role_id");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("title");

                    b.Property<short>("TypeId")
                        .HasColumnType("smallint")
                        .HasColumnName("type_id");

                    b.HasKey("Id");

                    b.HasIndex("SenderRoleId");

                    b.HasIndex("TypeId")
                        .HasDatabaseName("ix_notifications_type");

                    b.ToTable("notifications", "edutrack");

                    b.HasData(
                        new
                        {
                            Id = "n3",
                            IsRead = false,
                            Message = "Antrenman saatlerinde düzenleme yapılmıştır.",
                            SenderRoleId = (short)2,
                            Timestamp = new DateTime(2024, 4, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Haftalık Program Güncellemesi",
                            TypeId = (short)1
                        },
                        new
                        {
                            Id = "n1",
                            IsRead = false,
                            Message = "U19 Futbol Elit Grubu dersi 15 dakika içinde başlayacak.",
                            Timestamp = new DateTime(2024, 4, 1, 11, 30, 0, 0, DateTimeKind.Utc),
                            Title = "Ders Başlıyor",
                            TypeId = (short)2
                        },
                        new
                        {
                            Id = "n2",
                            IsRead = true,
                            Message = "Mehmet Kaya bugünkü matematik dersinde \"Var\" olarak işaretlendi.",
                            Timestamp = new DateTime(2024, 4, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Yoklama Alındı",
                            TypeId = (short)3
                        });
                });

            modelBuilder.Entity("EduTrackApi.Domain.Entities.NotificationType", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("notification_types", "edutrack");

                    b.HasData(
                        new
                        {
                            Id = (short)1,
                            Code = "ANNOUNCEMENT",
                            Name = "Duyuru"
                        },
                        new
                        {
                            Id = (short)2,
                            Code = "UPCOMING_CLASS",
                            Name = "Yaklaşan Ders"
                        },
                        new
                        {
                            Id = (short)3,
                            Code = "ATTENDANCE_UPDATE",
                            Name = "Yoklama Güncellemesi"
                        });
                });

            modelBuilder.Entity("EduTrackApi.Domain.Entities.ParentChild", b =>
                {
                    b.Property<string>("ParentId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("parent_id");

                    b.Property<string>("ChildId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("child_id");

                    b.HasKey("ParentId", "ChildId");

                    b.HasIndex("ChildId");

                    b.ToTable("parent_children", "edutrack");

                    b.HasData(
                        new
                        {
                            ParentId = "u3",
                            ChildId = "u2"
                        },
                        new
                        {
                            ParentId = "u3",
                            ChildId = "u9"
                        });
                });

            modelBuilder.Entity("EduTrackApi.Domain.Entities.Payment", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("amount");

                    b.Property<string>("CourseId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("course_id");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("due_date");

                    b.Property<string>("Method")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("method");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("paid_at");

                    b.Property<short>("StatusId")
                        .HasColumnType("smallint")
                        .HasColumnName("status_id");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("student_id");

                    b.HasKey("Id");

                    b.HasIndex("CourseId")
                        .HasDatabaseName("ix_payments_course");

                    b.HasIndex("StatusId");

                    b.HasIndex("StudentId")
                        .HasDatabaseName("ix_payments_student");

                    b.ToTable("payments", "edutrack");

                    b.HasData(
                        new
                        {
                            Id = "pay1",
                            Amount = 1500m,
                            CourseId = "crs1",
                            DueDate = new DateTime(2024, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            StatusId = (short)3,
                            StudentId = "u2"
                        },
                        new
                        {
                            Id = "pay2",
                            Amount = 1200m,
                            CourseId = "crs2",
                            DueDate = new DateTime(2024, 6, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Method = "Credit Card",
                            PaidAt = new DateTime(2024, 6, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            StatusId = (short)2,
                            StudentId = "u2"
                        },
                        new
                        {
                            Id = "pay3",
                            Amount = 1500m,
                            CourseId = "crs1",
                            DueDate = new DateTime(2024, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Method = "Manual",
                            StatusId = (short)1,
                            StudentId = "u2"
                        },
                        new
                        {
                            Id = "pay4",
                            Amount = 1500m,
                            CourseId = "crs1",
                            DueDate = new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Method = "Manual",
                            PaidAt = new DateTime(2024, 5, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            StatusId = (short)2,
                            StudentId = "u9"
                        });
                });

            modelBuilder.Entity("EduTrackApi.Domain.Entities.PaymentStatus", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("payment_statuses", "edutrack");

                    b.HasData(
                        new
                        {
                            Id = (short)1,
                            Code = "PENDING",
                            Name = "Beklemede"
                        },
                        new
                        {
                            Id = (short)2,
                            Code = "PAID",
                            Name = "Ödendi"
                        },
                        new
                        {
                            Id = (short)3,
                            Code = "OVERDUE",
                            Name = "Gecikmiş"
                        });
                });

            modelBuilder.Entity("EduTrackApi.Domain.Entities.School", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("schools", "edutrack");

                    b.HasData(
                        new
                        {
                            Id = "school-a",
                            Name = "Okul A"
                        },
                        new
                        {
                            Id = "school-b",
                            Name = "Okul B"
                        });
                });

            modelBuilder.Entity("EduTrackApi.Domain.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<string>("Avatar")
                        .HasColumnType("text")
                        .HasColumnName("avatar");

                    b.Property<string>("Bio")
                        .HasColumnType("text")
                        .HasColumnName("bio");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("birth_date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("Gender")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("gender");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("phone_number");

                    b.Property<short>("RoleId")
                        .HasColumnType("smallint")
                        .HasColumnName("role_id");

                    b.Property<string>("SchoolId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("school_id");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.HasIndex("SchoolId");

                    b.ToTable("users", "edutrack");

                    b.HasData(
                        new
                        {
                            Id = "admin",
                            Address = "İstanbul, Türkiye",
                            Avatar = "https://picsum.photos/seed/admin/200",
                            BirthDate = new DateTime(1990, 5, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@edutrack.com",
                            Gender = "Kadın",
                            Name = "Zeynep Sistem",
                            PhoneNumber = "0555 111 22 33",
                            RoleId = (short)1
                        },
                        new
                        {
                            Id = "u4",
                            Avatar = "https://picsum.photos/seed/u4/200",
                            Email = "canan@okul-a.com",
                            Name = "Canan Sert",
                            PhoneNumber = "0555 444 55 66",
                            RoleId = (short)2,
                            SchoolId = "school-a"
                        },
                        new
                        {
                            Id = "u1",
                            Avatar = "https://picsum.photos/seed/u1/200",
                            Bio = "15 yıllık profesyonel futbol antrenörlüğü tecrübesi.",
                            Email = "ahmet@okul-a.com",
                            Name = "Ahmet Yılmaz",
                            PhoneNumber = "0532 123 45 67",
                            RoleId = (short)3,
                            SchoolId = "school-a"
                        },
                        new
                        {
                            Id = "u3",
                            Avatar = "https://picsum.photos/seed/u3/200",
                            Email = "ayse@veli.com",
                            Name = "Ayşe Demir",
                            RoleId = (short)4
                        },
                        new
                        {
                            Id = "u2",
                            Address = "Ankara, Türkiye",
                            Avatar = "https://picsum.photos/seed/u2/200",
                            BirthDate = new DateTime(2008, 10, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "mehmet@okul-a.com",
                            Gender = "Erkek",
                            Name = "Mehmet Kaya",
                            PhoneNumber = "0505 987 65 43",
                            RoleId = (short)5,
                            SchoolId = "school-a"
                        },
                        new
                        {
                            Id = "u9",
                            Avatar = "https://picsum.photos/seed/u9/200",
                            Email = "ali@okul-a.com",
                            Name = "Ali Vural",
                            RoleId = (short)5,
                            SchoolId = "school-a"
                        },
                        new
                        {
                            Id = "u5",
                            Avatar = "https://picsum.photos/seed/u5/200",
                            Email = "bulent@okul-b.com",
                            Name = "Bülent Arın",
                            RoleId = (short)2,
                            SchoolId = "school-b"
                        },
                        new
                        {
                            Id = "u7",
                            Avatar = "https://picsum.photos/seed/u7/200",
                            Bio = "Matematik Olimpiyatları koordinatörü.",
                            Email = "fatma@okul-a.com",
                            Name = "Fatma Şahin",
                            RoleId = (short)3,
                            SchoolId = "school-a"
                        },
                        new
                        {
                            Id = "u8",
                            Avatar = "https://picsum.photos/seed/u8/200",
                            Email = "murat@okul-a.com",
                            Name = "Murat Can",
                            RoleId = (short)3,
                            SchoolId = "school-a"
                        });
                });

            modelBuilder.Entity("EduTrackApi.Domain.Entities.UserBadge", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("user_id");

                    b.Property<string>("BadgeId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("badge_id");

                    b.Property<DateTime>("AwardedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("awarded_at");

                    b.HasKey("UserId", "BadgeId");

                    b.HasIndex("BadgeId");

                    b.ToTable("user_badges", "edutrack");

                    b.HasData(
                        new
                        {
                            UserId = "u2",
                            BadgeId = "bg1",
                            AwardedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            UserId = "u2",
                            BadgeId = "bg2",
                            AwardedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            UserId = "u2",
                            BadgeId = "bg3",
                            AwardedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            UserId = "u2",
                            BadgeId = "bg4",
                            AwardedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            UserId = "u2",
                            BadgeId = "bg5",
                            AwardedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            UserId = "u9",
                            BadgeId = "bg1",
                            AwardedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("EduTrackApi.Domain.Entities.UserRole", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("user_roles", "edutrack");

                    b.HasData(
                        new
                        {
                            Id = (short)1,
                            Code = "SYSTEM_ADMIN",
                            Name = "Sistem Yöneticisi"
                        },
                        new
                        {
                            Id = (short)2,
                            Code = "SCHOOL_ADMIN",
                            Name = "Okul Yöneticisi"
                        },
                        new
                        {
                            Id = (short)3,
                            Code = "TEACHER",
                            Name = "Eğitmen"
                        },
                        new
                        {
                            Id = (short)4,
                            Code = "PARENT",
                            Name = "Veli"
                        },
                        new
                        {
                            Id = (short)5,
                            Code = "STUDENT",
                            Name = "Öğrenci"
                        });
                });

            modelBuilder.Entity("EduTrackApi.Domain.Entities.Course", b =>
                {
                    b.HasOne("EduTrackApi.Domain.Entities.Branch", "Branch")
                        .WithMany("Courses")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EduTrackApi.Domain.Entities.Category", "Category")
                        .WithMany("Courses")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EduTrackApi.Domain.Entities.School", "School")
                        .WithMany("Courses")
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EduTrackApi.Domain.Entities.User", "Teacher")
                        .WithMany("CoursesAsTeacher")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("Category");

                    b.Navigation("School");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("EduTrackApi.Domain.Entities.CourseSchedule", b =>
                {
                    b.HasOne("EduTrackApi.Domain.Entities.Course", "Course")
                        .WithMany("Schedules")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("EduTrackApi.Domain.Entities.CourseStudent", b =>
                {
                    b.HasOne("EduTrackApi.Domain.Entities.Course", "Course")
                        .WithMany("CourseStudents")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EduTrackApi.Domain.Entities.User", "Student")
                        .WithMany("CourseStudents")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("EduTrackApi.Domain.Entities.Notification", b =>
                {
                    b.HasOne("EduTrackApi.Domain.Entities.UserRole", "SenderRole")
                        .WithMany("NotificationsAsSenderRole")
                        .HasForeignKey("SenderRoleId");

                    b.HasOne("EduTrackApi.Domain.Entities.NotificationType", "Type")
                        .WithMany("Notifications")
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SenderRole");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("EduTrackApi.Domain.Entities.ParentChild", b =>
                {
                    b.HasOne("EduTrackApi.Domain.Entities.User", "Child")
                        .WithMany("ParentChildrenAsChild")
                        .HasForeignKey("ChildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EduTrackApi.Domain.Entities.User", "Parent")
                        .WithMany("ParentChildrenAsParent")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Child");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("EduTrackApi.Domain.Entities.Payment", b =>
                {
                    b.HasOne("EduTrackApi.Domain.Entities.Course", "Course")
                        .WithMany("Payments")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EduTrackApi.Domain.Entities.PaymentStatus", "Status")
                        .WithMany("Payments")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EduTrackApi.Domain.Entities.User", "Student")
                        .WithMany("Payments")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Status");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("EduTrackApi.Domain.Entities.User", b =>
                {
                    b.HasOne("EduTrackApi.Domain.Entities.UserRole", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EduTrackApi.Domain.Entities.School", "School")
                        .WithMany("Users")
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Role");

                    b.Navigation("School");
                });

            modelBuilder.Entity("EduTrackApi.Domain.Entities.UserBadge", b =>
                {
                    b.HasOne("EduTrackApi.Domain.Entities.Badge", "Badge")
                        .WithMany("UserBadges")
                        .HasForeignKey("BadgeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EduTrackApi.Domain.Entities.User", "User")
                        .WithMany("UserBadges")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Badge");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EduTrackApi.Domain.Entities.Badge", b =>
                {
                    b.Navigation("UserBadges");
                });

            modelBuilder.Entity("EduTrackApi.Domain.Entities.Branch", b =>
                {
                    b.Navigation("Courses");
                });

            modelBuilder.Entity("EduTrackApi.Domain.Entities.Category", b =>
                {
                    b.Navigation("Courses");
                });

            modelBuilder.Entity("EduTrackApi.Domain.Entities.Course", b =>
                {
                    b.Navigation("CourseStudents");

                    b.Navigation("Payments");

                    b.Navigation("Schedules");
                });

            modelBuilder.Entity("EduTrackApi.Domain.Entities.NotificationType", b =>
                {
                    b.Navigation("Notifications");
                });

            modelBuilder.Entity("EduTrackApi.Domain.Entities.PaymentStatus", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("EduTrackApi.Domain.Entities.School", b =>
                {
                    b.Navigation("Courses");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("EduTrackApi.Domain.Entities.User", b =>
                {
                    b.Navigation("CourseStudents");

                    b.Navigation("CoursesAsTeacher");

                    b.Navigation("ParentChildrenAsChild");

                    b.Navigation("ParentChildrenAsParent");

                    b.Navigation("Payments");

                    b.Navigation("UserBadges");
                });

            modelBuilder.Entity("EduTrackApi.Domain.Entities.UserRole", b =>
                {
                    b.Navigation("NotificationsAsSenderRole");

                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
